### ISSUE TITLE
JRELoadError on Startup [macOS]

### ISSUE THREAD

**Issue by edwardloveall** [robertjanetzko/LegendsBrowser#11]
Hello,

I'm running Mac OS X 10.11.6 (15G1004). I downloaded the DMG, copied the application to my ~/Applications folder and opened the app. It immediately gave me a dialog box saying nothing but **JRELoadError**

Anything I can try?

**Comment by robertjanetzko** [comment]
looks like you are missing the Java Runtime or the right version. If you open a terminal and type `java -version` it should say "version 1.8". If not you can download the MacOS JRE from here: https://www.java.com/de/download/

**Comment by edwardloveall** [comment]
Ah I'm running version 1.6.0_65. Maybe that comes on mac by default? I'll try downloading that and see what happens

**Comment by edwardloveall** [comment]
So interestingly, I installed java from that page but `java -version` still shows 1.6.0_65. However the app works! Must be a path issue. Thanks for the assist. I'll close this and open other issues if I find them.
