### ISSUE TITLE
Problem when loading from path containing spaces (bug with processed .zip)

### ISSUE THREAD

**Issue by fricy** [robertjanetzko/LegendsBrowser#2]
Loading World
Illegal character in opaque part at index 64: jar:file:/Users/fricy/Applications/Macnewbie_10.4/Macnewbie/User Generated Content/Legends/region1_legends_exports/region1-00005-01-01-legends_archive.zip...

If I remove the spaces from User Generated Content it loads. Curiously the Browser is able to load "unprocessed" legends from the "Dwarf Fortress" folder which also contains spaces.

Version 1.06 and 1.07 both [OSX]

**Comment by robertjanetzko** [comment]
thx, already fixed it in b7148ad5079f8aaa991d7e316c12baa74ba502aa
expect an updated release this weekend
