### ISSUE TITLE
.dmg file fails to open

### ISSUE THREAD

**Issue by thecodewarrior** [robertjanetzko/LegendsBrowser#25]
When trying to open the .dmg release I am getting an error saying there are `no mountable file systems`. I've worked out that the issue turned up somewhere between the 1.13 and 1.14 releases. If you don't have a mac I'd be happy to test .dmg files for you.

![untitled](https://user-images.githubusercontent.com/5467669/37181227-f811a14e-22e0-11e8-8f24-959157678016.png)

**Comment by robertjanetzko** [comment]
I have. and I can open the .dmg I created as well as the ones downloaded from github and DFFD. Did you validate the checksum of your download with the one shown on DFFD?

**Comment by lethosor** [comment]
What macOS version was it created on?

**Comment by robertjanetzko** [comment]
10.13.2 and according to https://github.com/federkasten/appbundle-maven-plugin/blob/master/src/main/java/sh/tak/appbundler/CreateApplicationBundleMojo.java#L416 it just uses the hdiutil command.

**Comment by robertjanetzko** [comment]
@thecodewarrior which version of macOS are you trying to open it on? Seems the image uses APFS which probably won't work before 10.13

**Comment by lethosor** [comment]
Are you sure it's not making an APFS disk image or something like that, then? That wouldn't work on older versions as far as I know.

**Comment by robertjanetzko** [comment]
I changed the file system to HFS+ (hdiutil used APFS as default on 10.13) and updated the 1.17.1 image here and on DFFD. Let me know if the problem still exists.

**Comment by thecodewarrior** [comment]
Works perfectly now. 👍
