### ISSUE TITLE
Typo in updated exportlegends script

### ISSUE THREAD

**Issue by fricy** [robertjanetzko/LegendsBrowser#4]
Line 162 should be:  
`file:write("\t\t<style>"..(df.written_content_style[styleV] or styleV).."</style>\n")`

instead of closing with **/type**:  
`file:write("\t\t<style>"..(df.written_content_style[styleV] or styleV).."</type>\n")`

**Comment by robertjanetzko** [comment]
thx, also already fixed (try the latest version of exportlegends.lua)

**Comment by robertjanetzko** [comment]
the bug was in the forum post, I used the url from the wrong branch ;)
this should work
https://raw.githubusercontent.com/robertjanetzko/dfhack/additional-exports/scripts/exportlegends.lua
