### ISSUE TITLE
Legends Browser crashed immediately after launch (OS X)

### ISSUE THREAD

**Issue by DKraeff** [robertjanetzko/LegendsBrowser#69]
I downloaded the latest version of Legends Browser for mac OS (1.19.2), open the .dmg file and moved the application into my DF folder. However, the moment I open the application, it closes. The icon appears at my bottom bow for less than a second, after which is closes, it doesn't even give me an error message.

**Comment by robertjanetzko** [comment]
did you get a popup that says "untrusted developer" (or something like that)? If yes, you need to go to your system preferences > security > gerneral. There should be an "open anyways" button. 
More info here: https://www.macworld.co.uk/how-to/mac-software/mac-app-unidentified-developer-3669596

**Comment by DKraeff** [comment]
No, I didn't. The application just closes the second I open it, no messages. I tried moving it into the 'Utilities' folder of the LazyMacPac and open it from there, but nothing changed.

**Comment by robertjanetzko** [comment]
did you check the security preferences?
you can try adding the exception in a terminal: https://osxdaily.com/2015/07/15/add-remove-gatekeeper-app-command-line-mac-os-x/
otherwise you should check the console if you get an error message there.

**Comment by masseymo** [comment]
I'm also had issues with the osx version. I get the message that it is damaged and should be moved to the bin. 
just some info:
osx 10.15.3
The newest version I can run unmodified is 1.18.2. 
 using xattr -cr on the app via terminal allowed it to run
