### ISSUE TITLE
Support Java 11

### ISSUE THREAD

**Issue by jangop** [robertjanetzko/LegendsBrowser#76]
Ubuntu must have recently updated its default java runtime. Launching (via `java -jar legendsbrowser-1.19.2.jar`) now gives:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
```

After reverting to Java 8 (`sudo update-alternatives --config java`) LegendsBrowser launches fine.

**Comment by lethosor** [comment]
Looks to me like the `openjdk-11-jre` package contains `libawt_xawt.so` - do you have that package installed?

**Comment by jangop** [comment]
Thank you, my bad. I seemingly don't understand java dependencies.
