### ISSUE TITLE
What license is LegendsBrowser under?

### ISSUE THREAD

**Issue by TC01** [robertjanetzko/LegendsBrowser#9]
Hi,

I notice you mention that "LegendsBrowser is open source", but you do not specifically mention what license it's under. Can you please either license the software or make it explicit that the software is unlicensed and in the public domain?

For example, [see here](http://choosealicense.com/) for some more information if you want to pick a permissive or copyleft license.

**Comment by robertjanetzko** [comment]
thx for the reminder. i've now added the license file.
